In [16]:
import numpy as np
np.random.seed(42)

In [17]:
# Positional Encoding
def positional_encoding(seq_len, d_model):
    """
    Returns a matrix of shape (seq_len, d_model)
    With sinusoidal positional encodings
    """
    PE = np.zeros((seq_len, d_model))
    for pos in range(seq_len):
        for i in range(0, d_model, 2):
            PE[pos, i] = np.sin(pos / (10000 ** (i / d_model)))
            if i+1 < d_model:
                PE[pos, i+1] = np.cos(pos / (10000 ** (i / d_model)))
    return PE

seq_len = 5
d_model = 6
PE = positional_encoding(seq_len, d_model)

In [18]:
print("positional encoding shape :", PE.shape)
print(PE)

positional encoding shape : (5, 6)
[[ 0.          1.          0.          1.          0.          1.        ]
 [ 0.84147098  0.54030231  0.04639922  0.99892298  0.00215443  0.99999768]
 [ 0.90929743 -0.41614684  0.0926985   0.99569422  0.00430886  0.99999072]
 [ 0.14112001 -0.9899925   0.1387981   0.9903207   0.00646326  0.99997911]
 [-0.7568025  -0.65364362  0.18459872  0.98281398  0.00861763  0.99996287]]
